### ISSUE TITLE
为什么用GitHub的actions构建出来的安装包安装不了呢？

### ISSUE THREAD

**Issue by hong26** [CatVodTVOfficial/TVBoxOSC#18]
安装提示安装包解析出错，是什么原因呢？

**Comment by psk107520** [comment]
先签名

**Comment by hong26** [comment]
> 先签名

请问要如何签名呢？

**Comment by huxubo** [comment]
> > 先签名
> 
> 请问要如何签名呢？

MT管理器，ApktoolM等等都能签名

**Comment by hong26** [comment]
感谢，已经解决了

> > > 先签名
> > 
> > 
> > 请问要如何签名呢？
> 
> MT管理器，ApktoolM等等都能签名

感谢，已经解决了
