### ISSUE TITLE
手机k50pro本地化后无法显示电影，电视剧等分类，用的以前猫接口，是接口有问题吗？

### ISSUE THREAD

**Issue by jellywang6** [CatVodTVOfficial/TVBoxOSC#23]
本地格式clan://localhost/tvbox/Tangsan99999/peizhi.json

**Comment by sandeli** [comment]
你这个肯定是本地化期间哪里有错误

**Comment by jellywang6** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by jellywang6** [comment]
> 

我改了根目录里面的本名叫cat的文件夹，文件夹名字改成tvbox就不行了

**Comment by jellywang6** [comment]
只能用vivitv里面的6.19号的接口，6.21号的新接口不能用
